/**
 * MPLADS Monitoring and Anomaly Detection Analytics Platform
 * Realistic but strictly fictional mock datasets for frontend simulation
 * All monetary amounts represent Indian administrative figures (₹ Lakhs / ₹ Crores).
 */

export const MACRO_METRICS = {
  totalProjects: 1428,
  completedProjects: 892,
  ongoingProjects: 456,
  stalledProjects: 80,
  totalSanctionedCr: 245.50,
  totalExpenditureCr: 188.20,
  totalReleasedCr: 215.80,
  utilizationRate: 76.66,
  flaggedProjects: 80,
  resolvedAnomalies: 26,
  pendingAuditReviews: 54,
  lastUpdated: '2025-03-28T10:30:00Z',
  activeFiscalYear: 'FY 2024-25',
};

export const SECTORS = [
  'Rural Connectivity & Roads',
  'Drinking Water Facilities',
  'Primary Health Infrastructure',
  'Education & Libraries',
  'Community Sanitation Units',
  'Renewable Energy & Streetlighting',
];

export const DISTRICTS = [
  { id: 'dst-1', name: 'Devgarh', state: 'Madhya Pradesh', totalWorks: 245, sanctionedCr: 42.10, expenditureCr: 34.50, utilizationRate: 81.9, flagsCount: 11, lat: 24.12, lng: 77.85 },
  { id: 'dst-2', name: 'Rampur North', state: 'Madhya Pradesh', totalWorks: 210, sanctionedCr: 36.80, expenditureCr: 29.10, utilizationRate: 79.1, flagsCount: 8, lat: 24.58, lng: 78.45 },
  { id: 'dst-3', name: 'Sundarnagar', state: 'Madhya Pradesh', totalWorks: 290, sanctionedCr: 51.20, expenditureCr: 37.60, utilizationRate: 73.4, flagsCount: 19, lat: 23.85, lng: 79.20 },
  { id: 'dst-4', name: 'Kalyanpur', state: 'Madhya Pradesh', totalWorks: 195, sanctionedCr: 33.40, expenditureCr: 27.80, utilizationRate: 83.2, flagsCount: 6, lat: 23.18, lng: 77.40 },
  { id: 'dst-5', name: 'Sitapur East', state: 'Madhya Pradesh', totalWorks: 238, sanctionedCr: 39.50, expenditureCr: 26.20, utilizationRate: 66.3, flagsCount: 22, lat: 23.50, lng: 78.90 },
  { id: 'dst-6', name: 'Anandpur', state: 'Madhya Pradesh', totalWorks: 130, sanctionedCr: 22.50, expenditureCr: 18.20, utilizationRate: 80.9, flagsCount: 7, lat: 22.95, lng: 78.20 },
  { id: 'dst-7', name: 'Vikramnagar', state: 'Madhya Pradesh', totalWorks: 120, sanctionedCr: 20.00, expenditureCr: 14.80, utilizationRate: 74.0, flagsCount: 7, lat: 24.30, lng: 79.50 },
];

export const SECTOR_PROGRESS_DATA = [
  { sector: 'Roads & Bridges', completed: 312, ongoing: 140, sanctioned: 45, totalCostCr: 88.4 },
  { sector: 'Drinking Water', completed: 210, ongoing: 85, sanctioned: 32, totalCostCr: 45.2 },
  { sector: 'Healthcare', completed: 115, ongoing: 62, sanctioned: 18, totalCostCr: 38.6 },
  { sector: 'Education', completed: 154, ongoing: 92, sanctioned: 28, totalCostCr: 42.1 },
  { sector: 'Sanitation', completed: 78, ongoing: 54, sanctioned: 14, totalCostCr: 21.0 },
  { sector: 'Solar & Lighting', completed: 23, ongoing: 23, sanctioned: 9, totalCostCr: 10.2 },
];

export const FUND_UTILIZATION_TREND = [
  { period: 'Q1 FY23', sanctionedCr: 120.0, releasedCr: 105.0, expendedCr: 82.4 },
  { period: 'Q2 FY23', sanctionedCr: 145.0, releasedCr: 130.0, expendedCr: 104.2 },
  { period: 'Q3 FY23', sanctionedCr: 170.0, releasedCr: 155.0, expendedCr: 125.8 },
  { period: 'Q4 FY23', sanctionedCr: 195.0, releasedCr: 178.0, expendedCr: 148.5 },
  { period: 'Q1 FY24', sanctionedCr: 215.0, releasedCr: 192.0, expendedCr: 161.2 },
  { period: 'Q2 FY24', sanctionedCr: 230.0, releasedCr: 205.0, expendedCr: 174.0 },
  { period: 'Q3 FY24', sanctionedCr: 240.0, releasedCr: 210.0, expendedCr: 182.5 },
  { period: 'Q4 FY24', sanctionedCr: 245.5, releasedCr: 215.8, expendedCr: 188.2 },
];

export const RECENT_ANOMALY_ALERTS = [
  {
    id: 'ALT-801',
    workCode: 'MPLADS-2024-0412',
    workTitle: 'Construction of Community Health Center Ward Block',
    district: 'Sitapur East',
    constituency: 'Sitapur Parliamentary',
    category: 'Progress-Disbursement Divergence',
    triggerDescription: 'Reported 92% fund expenditure with physical progress recorded at 24%. Statistical outlier in progress-to-spend ratio.',
    severity: 'high',
    sanctionedAmountLakhs: 48.50,
    expenditureLakhs: 44.62,
    physicalProgress: 24,
    detectedDate: '2025-03-24',
    auditStatus: 'Pending Review',
    modelConfidence: 0.94,
  },
  {
    id: 'ALT-802',
    workCode: 'MPLADS-2024-0198',
    workTitle: 'Installation of Solar Streetlighting Units (Phase 2)',
    district: 'Sundarnagar',
    constituency: 'Sundarnagar Central',
    category: 'Timeline Inactivity > 150 Days',
    triggerDescription: 'Zero milestone verification updates logged for 164 days post initial mobilization advance.',
    severity: 'medium',
    sanctionedAmountLakhs: 22.00,
    expenditureLakhs: 11.00,
    physicalProgress: 35,
    detectedDate: '2025-03-22',
    auditStatus: 'Field Inquiry Assigned',
    modelConfidence: 0.86,
  },
  {
    id: 'ALT-803',
    workCode: 'MPLADS-2023-1104',
    workTitle: 'Upgradation of Link Road from Gram Panchayat to NH-44',
    district: 'Devgarh',
    constituency: 'Devgarh South',
    category: 'Unrevised Cost Variance',
    triggerDescription: 'Expenditure exceeded initial administrative sanction by 29.4% without documented revised administrative approval.',
    severity: 'high',
    sanctionedAmountLakhs: 35.00,
    expenditureLakhs: 45.30,
    physicalProgress: 88,
    detectedDate: '2025-03-18',
    auditStatus: 'Pending Review',
    modelConfidence: 0.91,
  },
  {
    id: 'ALT-804',
    workCode: 'MPLADS-2024-0651',
    workTitle: 'Deep Borewell and Solar Dual-Pump Piped Water Supply',
    district: 'Sitapur East',
    constituency: 'Sitapur Rural',
    category: 'Delayed Utilization Certificate',
    triggerDescription: 'Project physically 100% complete for 180+ days; final Utilization Certificate (UC) pending nodal sign-off.',
    severity: 'low',
    sanctionedAmountLakhs: 16.50,
    expenditureLakhs: 16.50,
    physicalProgress: 100,
    detectedDate: '2025-03-15',
    auditStatus: 'Documentation Follow-up',
    modelConfidence: 0.78,
  },
  {
    id: 'ALT-805',
    workCode: 'MPLADS-2024-0823',
    workTitle: 'Construction of Multipurpose Cyclone Shelter & Community Hall',
    district: 'Sundarnagar',
    constituency: 'Sundarnagar Coastal',
    category: 'Progress-Disbursement Divergence',
    triggerDescription: '85% disbursement with foundations partially laid (20% physical inspection index).',
    severity: 'high',
    sanctionedAmountLakhs: 65.00,
    expenditureLakhs: 55.25,
    physicalProgress: 20,
    detectedDate: '2025-03-10',
    auditStatus: 'Pending Review',
    modelConfidence: 0.95,
  },
];

export const STATES = [
  'Madhya Pradesh',
  'Maharashtra',
  'Rajasthan',
  'Uttar Pradesh',
  'Odisha',
];

export const FINANCIAL_YEARS = [
  'FY 2024-25',
  'FY 2023-24',
  'FY 2022-23',
];

export const PROJECT_STATUSES = [
  'Completed',
  'Ongoing',
  'Delayed',
  'Cancelled',
];

export const RISK_LEVELS = [
  'Normal',
  'Low Risk',
  'Medium Risk',
  'High Risk',
];

export const MOCK_PROJECTS = [
  {
    id: 'PRJ-100',
    code: 'MPLADS-001',
    title: 'Construction of Community Hall',
    state: 'Madhya Pradesh',
    district: 'Indore',
    constituency: 'Indore Parliamentary',
    mpName: 'Hon. Shankar Lalwani (Fictional)',
    workType: 'Community Sanitation Units',
    sector: 'Community Infrastructure',
    implementingAgency: 'Indore Municipal Technical Cell',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-03-01',
    startDate: '2024-03-15',
    expectedCompletion: '2024-12-15',
    sanctionAmountLakhs: 50.00,
    releasedAmountLakhs: 40.00,
    expenditureLakhs: 34.00,
    physicalProgress: 68,
    status: 'Ongoing',
    riskLevel: 'Medium Risk',
    reviewFlag: true,
    flagCategory: 'Progress-Disbursement Divergence',
    flagSeverity: 'medium',
    flagReason: 'Expenditure velocity at 68% with slow initial foundation sign-offs. Flagged for nodal milestone verification.',
    anomalyReason: 'Expenditure velocity at 68% with slow initial foundation sign-offs. Flagged for nodal milestone verification.',
  },
  {
    id: 'PRJ-101',
    code: 'MPLADS-2024-0412',
    title: 'Construction of Community Health Center Ward Block',
    state: 'Madhya Pradesh',
    district: 'Sitapur East',
    constituency: 'Sitapur Parliamentary',
    mpName: 'Hon. Rajesh V. Sharma (Fictional)',
    workType: 'Primary Health Infrastructure',
    sector: 'Primary Health Infrastructure',
    implementingAgency: 'District Rural Development Agency (DRDA)',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-02-14',
    startDate: '2024-02-14',
    expectedCompletion: '2024-11-30',
    sanctionAmountLakhs: 48.50,
    releasedAmountLakhs: 46.00,
    expenditureLakhs: 44.62,
    physicalProgress: 24,
    status: 'Ongoing',
    riskLevel: 'High Risk',
    reviewFlag: true,
    flagCategory: 'Progress-Disbursement Divergence',
    flagSeverity: 'high',
    flagReason: 'Reported 92% fund expenditure with physical progress recorded at 24%. Statistical outlier in progress-to-spend ratio flagged for administrative review.',
    anomalyReason: 'Reported 92% fund expenditure with physical progress recorded at 24%. Statistical outlier in progress-to-spend ratio flagged for administrative review.',
  },
  {
    id: 'PRJ-102',
    code: 'MPLADS-2024-0198',
    title: 'Installation of Solar Streetlighting Units (Phase 2)',
    state: 'Madhya Pradesh',
    district: 'Sundarnagar',
    constituency: 'Sundarnagar Central',
    mpName: 'Hon. Ananya Sen (Fictional)',
    workType: 'Renewable Energy & Streetlighting',
    sector: 'Renewable Energy & Streetlighting',
    implementingAgency: 'Public Works Department (Electrical)',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-04-10',
    startDate: '2024-04-10',
    expectedCompletion: '2024-10-15',
    sanctionAmountLakhs: 22.00,
    releasedAmountLakhs: 18.00,
    expenditureLakhs: 11.00,
    physicalProgress: 35,
    status: 'Delayed',
    riskLevel: 'Medium Risk',
    reviewFlag: true,
    flagCategory: 'Timeline Inactivity > 150 Days',
    flagSeverity: 'medium',
    flagReason: 'Zero milestone verification updates logged for 164 days post initial mobilization advance.',
    anomalyReason: 'Zero milestone verification updates logged for 164 days post initial mobilization advance.',
  },
  {
    id: 'PRJ-103',
    code: 'MPLADS-2023-1104',
    title: 'Upgradation of Link Road from Gram Panchayat to NH-44',
    state: 'Madhya Pradesh',
    district: 'Devgarh',
    constituency: 'Devgarh South',
    mpName: 'Hon. K. R. Meena (Fictional)',
    workType: 'Rural Connectivity & Roads',
    sector: 'Rural Connectivity & Roads',
    implementingAgency: 'State Rural Road Authority',
    financialYear: 'FY 2023-24',
    sanctionDate: '2023-10-18',
    startDate: '2023-10-18',
    expectedCompletion: '2024-06-30',
    sanctionAmountLakhs: 35.00,
    releasedAmountLakhs: 35.00,
    expenditureLakhs: 45.30,
    physicalProgress: 88,
    status: 'Delayed',
    riskLevel: 'High Risk',
    reviewFlag: true,
    flagCategory: 'Unrevised Cost Variance',
    flagSeverity: 'high',
    flagReason: 'Expenditure exceeded initial administrative sanction by 29.4% without documented revised administrative approval.',
    anomalyReason: 'Expenditure exceeded initial administrative sanction by 29.4% without documented revised administrative approval.',
  },
  {
    id: 'PRJ-104',
    code: 'MPLADS-2024-0045',
    title: 'Modern Science Laboratory and Library Building in Govt High School',
    state: 'Madhya Pradesh',
    district: 'Kalyanpur',
    constituency: 'Kalyanpur Central',
    mpName: 'Hon. P. S. Chauhan (Fictional)',
    workType: 'Education & Libraries',
    sector: 'Education & Libraries',
    implementingAgency: 'District Education Infrastructure Unit',
    financialYear: 'FY 2023-24',
    sanctionDate: '2024-01-20',
    startDate: '2024-01-20',
    expectedCompletion: '2024-09-15',
    sanctionAmountLakhs: 32.50,
    releasedAmountLakhs: 32.50,
    expenditureLakhs: 31.80,
    physicalProgress: 100,
    status: 'Completed',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-105',
    code: 'MPLADS-2024-0319',
    title: 'Piped Drinking Water Scheme with Reverse Osmosis Plant',
    state: 'Madhya Pradesh',
    district: 'Devgarh',
    constituency: 'Devgarh Central',
    mpName: 'Hon. K. R. Meena (Fictional)',
    workType: 'Drinking Water Facilities',
    sector: 'Drinking Water Facilities',
    implementingAgency: 'Public Health Engineering Dept (PHED)',
    financialYear: 'FY 2023-24',
    sanctionDate: '2024-03-05',
    startDate: '2024-03-05',
    expectedCompletion: '2025-01-20',
    sanctionAmountLakhs: 28.00,
    releasedAmountLakhs: 25.00,
    expenditureLakhs: 21.50,
    physicalProgress: 75,
    status: 'Ongoing',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-106',
    code: 'MPLADS-2024-0651',
    title: 'Deep Borewell and Solar Dual-Pump Piped Water Supply',
    state: 'Madhya Pradesh',
    district: 'Sitapur East',
    constituency: 'Sitapur Rural',
    mpName: 'Hon. Rajesh V. Sharma (Fictional)',
    workType: 'Drinking Water Facilities',
    sector: 'Drinking Water Facilities',
    implementingAgency: 'Groundwater Survey & Development Agency',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-05-12',
    startDate: '2024-05-12',
    expectedCompletion: '2024-11-15',
    sanctionAmountLakhs: 16.50,
    releasedAmountLakhs: 16.50,
    expenditureLakhs: 16.50,
    physicalProgress: 100,
    status: 'Completed',
    riskLevel: 'Low Risk',
    reviewFlag: true,
    flagCategory: 'Delayed Utilization Certificate',
    flagSeverity: 'low',
    flagReason: 'Project physically complete for 180+ days; final Utilization Certificate (UC) pending nodal sign-off.',
    anomalyReason: 'Project physically complete for 180+ days; final Utilization Certificate (UC) pending nodal sign-off.',
  },
  {
    id: 'PRJ-107',
    code: 'MPLADS-2024-0711',
    title: 'Construction of Community Sanitation Complex for Rural Haat',
    state: 'Madhya Pradesh',
    district: 'Rampur North',
    constituency: 'Rampur Sadar',
    mpName: 'Hon. Sunita Devi (Fictional)',
    workType: 'Community Sanitation Units',
    sector: 'Community Sanitation Units',
    implementingAgency: 'Zilla Panchayat Engineering Wing',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-06-15',
    startDate: '2024-06-15',
    expectedCompletion: '2024-12-30',
    sanctionAmountLakhs: 14.80,
    releasedAmountLakhs: 14.80,
    expenditureLakhs: 13.90,
    physicalProgress: 95,
    status: 'Ongoing',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-108',
    code: 'MPLADS-2024-0823',
    title: 'Construction of Multipurpose Cyclone Shelter & Community Hall',
    state: 'Madhya Pradesh',
    district: 'Sundarnagar',
    constituency: 'Sundarnagar Coastal',
    mpName: 'Hon. Ananya Sen (Fictional)',
    workType: 'Primary Health Infrastructure',
    sector: 'Primary Health Infrastructure',
    implementingAgency: 'State Disaster Management Cell',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-07-02',
    startDate: '2024-07-02',
    expectedCompletion: '2025-03-31',
    sanctionAmountLakhs: 65.00,
    releasedAmountLakhs: 58.00,
    expenditureLakhs: 55.25,
    physicalProgress: 20,
    status: 'Ongoing',
    riskLevel: 'High Risk',
    reviewFlag: true,
    flagCategory: 'Progress-Disbursement Divergence',
    flagSeverity: 'high',
    flagReason: '85% disbursement with foundations partially laid (20% physical inspection index).',
    anomalyReason: '85% disbursement with foundations partially laid (20% physical inspection index). Flagged for milestone inspection.',
  },
  {
    id: 'PRJ-109',
    code: 'MPLADS-2024-0940',
    title: 'Concrete Pavement and Drainage System in Ward 8 to 12',
    state: 'Madhya Pradesh',
    district: 'Anandpur',
    constituency: 'Anandpur Urban',
    mpName: 'Hon. Amit Verma (Fictional)',
    workType: 'Rural Connectivity & Roads',
    sector: 'Rural Connectivity & Roads',
    implementingAgency: 'Municipal Corporation Technical Cell',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-08-11',
    startDate: '2024-08-11',
    expectedCompletion: '2025-02-28',
    sanctionAmountLakhs: 41.20,
    releasedAmountLakhs: 35.00,
    expenditureLakhs: 32.40,
    physicalProgress: 70,
    status: 'Ongoing',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-110',
    code: 'MPLADS-2024-1014',
    title: 'Installation of High-Mast Solar Lighting at Market Squares',
    state: 'Madhya Pradesh',
    district: 'Vikramnagar',
    constituency: 'Vikramnagar East',
    mpName: 'Hon. Tarun Joshi (Fictional)',
    workType: 'Renewable Energy & Streetlighting',
    sector: 'Renewable Energy & Streetlighting',
    implementingAgency: 'Renewable Energy Development Agency',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-09-01',
    startDate: '2024-09-01',
    expectedCompletion: '2024-12-10',
    sanctionAmountLakhs: 18.00,
    releasedAmountLakhs: 18.00,
    expenditureLakhs: 17.60,
    physicalProgress: 100,
    status: 'Completed',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-111',
    code: 'MPLADS-2024-1122',
    title: 'Model Girls High School Digital Smart Classrooms',
    state: 'Maharashtra',
    district: 'Pune Rural',
    constituency: 'Baramati Parliamentary',
    mpName: 'Hon. Vilasrao Shinde (Fictional)',
    workType: 'Education & Libraries',
    sector: 'Education & Libraries',
    implementingAgency: 'Zilla Parishad Works Department',
    financialYear: 'FY 2023-24',
    sanctionDate: '2024-01-15',
    startDate: '2024-01-15',
    expectedCompletion: '2024-10-30',
    sanctionAmountLakhs: 38.00,
    releasedAmountLakhs: 38.00,
    expenditureLakhs: 36.20,
    physicalProgress: 90,
    status: 'Delayed',
    riskLevel: 'Medium Risk',
    reviewFlag: true,
    flagCategory: 'Timeline Drift',
    flagSeverity: 'medium',
    flagReason: 'Project duration exceeded original completion target date by 60+ days awaiting IT equipment procurement.',
    anomalyReason: 'Project duration exceeded original completion target date by 60+ days awaiting IT equipment procurement.',
  },
  {
    id: 'PRJ-112',
    code: 'MPLADS-2024-1185',
    title: 'Gravity-Fed Potable Drinking Water Supply Scheme',
    state: 'Maharashtra',
    district: 'Nagpur East',
    constituency: 'Nagpur Parliamentary',
    mpName: 'Hon. Devendra Patil (Fictional)',
    workType: 'Drinking Water Facilities',
    sector: 'Drinking Water Facilities',
    implementingAgency: 'Maharashtra Jeevan Pradhikaran',
    financialYear: 'FY 2023-24',
    sanctionDate: '2024-03-10',
    startDate: '2024-03-10',
    expectedCompletion: '2024-08-20',
    sanctionAmountLakhs: 24.50,
    releasedAmountLakhs: 24.50,
    expenditureLakhs: 24.10,
    physicalProgress: 100,
    status: 'Completed',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-113',
    code: 'MPLADS-2024-1230',
    title: 'Pre-fabricated Public Sanitation Complex at Market Yard',
    state: 'Maharashtra',
    district: 'Nashik South',
    constituency: 'Nashik Parliamentary',
    mpName: 'Hon. Sneha Kulkarni (Fictional)',
    workType: 'Community Sanitation Units',
    sector: 'Community Sanitation Units',
    implementingAgency: 'Municipal Council Technical Wing',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-05-18',
    startDate: '2024-05-18',
    expectedCompletion: '2024-11-30',
    sanctionAmountLakhs: 12.00,
    releasedAmountLakhs: 2.00,
    expenditureLakhs: 0.80,
    physicalProgress: 5,
    status: 'Cancelled',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: 'Project cancelled after municipal land rezoning conflict; initial token mobilization advance returned.',
    anomalyReason: 'Project cancelled after municipal land rezoning conflict; initial token mobilization advance returned.',
  },
  {
    id: 'PRJ-114',
    code: 'MPLADS-2023-0850',
    title: 'Bituminous Village Road Connectivity to State Highway 12',
    state: 'Rajasthan',
    district: 'Jaipur North',
    constituency: 'Jaipur Rural',
    mpName: 'Hon. Mahendra Rathore (Fictional)',
    workType: 'Rural Connectivity & Roads',
    sector: 'Rural Connectivity & Roads',
    implementingAgency: 'Public Works Department (Roads)',
    financialYear: 'FY 2023-24',
    sanctionDate: '2023-08-14',
    startDate: '2023-08-14',
    expectedCompletion: '2024-03-31',
    sanctionAmountLakhs: 52.00,
    releasedAmountLakhs: 52.00,
    expenditureLakhs: 51.00,
    physicalProgress: 100,
    status: 'Completed',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-115',
    code: 'MPLADS-2024-1310',
    title: 'Solar Tube-Well and Overhead Reservoir in Tribal Block',
    state: 'Rajasthan',
    district: 'Udaipur Rural',
    constituency: 'Udaipur Parliamentary',
    mpName: 'Hon. Kalpana Meena (Fictional)',
    workType: 'Drinking Water Facilities',
    sector: 'Drinking Water Facilities',
    implementingAgency: 'Groundwater Department',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-06-01',
    startDate: '2024-06-01',
    expectedCompletion: '2024-12-15',
    sanctionAmountLakhs: 29.50,
    releasedAmountLakhs: 22.00,
    expenditureLakhs: 18.20,
    physicalProgress: 45,
    status: 'Delayed',
    riskLevel: 'Medium Risk',
    reviewFlag: true,
    flagCategory: 'Strata Delay Verification',
    flagSeverity: 'medium',
    flagReason: 'Hard rock drilling challenge caused 45-day delay past initial completion schedule; rig replacement approved.',
    anomalyReason: 'Hard rock drilling challenge caused 45-day delay past initial completion schedule; rig replacement approved.',
  },
  {
    id: 'PRJ-116',
    code: 'MPLADS-2022-0490',
    title: 'Primary Health Sub-Center Maternity Ward Extension',
    state: 'Uttar Pradesh',
    district: 'Varanasi Rural',
    constituency: 'Varanasi Parliamentary',
    mpName: 'Hon. Alok Tripathy (Fictional)',
    workType: 'Primary Health Infrastructure',
    sector: 'Primary Health Infrastructure',
    implementingAgency: 'UP State Construction Corporation',
    financialYear: 'FY 2022-23',
    sanctionDate: '2022-11-10',
    startDate: '2022-11-10',
    expectedCompletion: '2023-08-30',
    sanctionAmountLakhs: 44.00,
    releasedAmountLakhs: 44.00,
    expenditureLakhs: 43.80,
    physicalProgress: 100,
    status: 'Completed',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-117',
    code: 'MPLADS-2023-0612',
    title: 'Composite Science Block & Reading Hall in Inter College',
    state: 'Uttar Pradesh',
    district: 'Lucknow West',
    constituency: 'Lucknow Central',
    mpName: 'Hon. Rameshwar Yadav (Fictional)',
    workType: 'Education & Libraries',
    sector: 'Education & Libraries',
    implementingAgency: 'District School Education Board',
    financialYear: 'FY 2023-24',
    sanctionDate: '2023-09-05',
    startDate: '2023-09-05',
    expectedCompletion: '2024-04-30',
    sanctionAmountLakhs: 30.00,
    releasedAmountLakhs: 28.50,
    expenditureLakhs: 27.50,
    physicalProgress: 80,
    status: 'Delayed',
    riskLevel: 'Low Risk',
    reviewFlag: true,
    flagCategory: 'Procurement Schedule Slip',
    flagSeverity: 'low',
    flagReason: 'Minor delay in final lab furnishing inspection; structural building finished.',
    anomalyReason: 'Minor delay in final lab furnishing inspection; structural building finished.',
  },
  {
    id: 'PRJ-118',
    code: 'MPLADS-2024-1422',
    title: 'Installation of Solar Streetlights along Canal Bund Road',
    state: 'Uttar Pradesh',
    district: 'Gorakhpur North',
    constituency: 'Gorakhpur Rural',
    mpName: 'Hon. Vijender Shukla (Fictional)',
    workType: 'Renewable Energy & Streetlighting',
    sector: 'Renewable Energy & Streetlighting',
    implementingAgency: 'Non-Conventional Energy Agency (NEDA)',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-07-20',
    startDate: '2024-07-20',
    expectedCompletion: '2024-10-30',
    sanctionAmountLakhs: 15.00,
    releasedAmountLakhs: 0.00,
    expenditureLakhs: 0.00,
    physicalProgress: 0,
    status: 'Cancelled',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: 'Scheme cancelled due to canal widening project overlapping alignment; no funds disbursed.',
    anomalyReason: 'Scheme cancelled due to canal widening project overlapping alignment; no funds disbursed.',
  },
  {
    id: 'PRJ-119',
    code: 'MPLADS-2024-1505',
    title: 'All-Weather Concrete Link Road and Culvert Construction',
    state: 'Odisha',
    district: 'Cuttack Rural',
    constituency: 'Cuttack Parliamentary',
    mpName: 'Hon. Manas Ranjan Das (Fictional)',
    workType: 'Rural Connectivity & Roads',
    sector: 'Rural Connectivity & Roads',
    implementingAgency: 'Rural Works Division, Odisha',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-04-18',
    startDate: '2024-04-18',
    expectedCompletion: '2025-01-31',
    sanctionAmountLakhs: 46.00,
    releasedAmountLakhs: 35.00,
    expenditureLakhs: 32.20,
    physicalProgress: 60,
    status: 'Ongoing',
    riskLevel: 'Normal',
    reviewFlag: false,
    flagCategory: null,
    flagSeverity: 'none',
    flagReason: null,
    anomalyReason: null,
  },
  {
    id: 'PRJ-120',
    code: 'MPLADS-2024-1580',
    title: 'Community Sanitation & Hygiene Block Near Pilgrimage Route',
    state: 'Odisha',
    district: 'Puri South',
    constituency: 'Puri Parliamentary',
    mpName: 'Hon. Pinaki Mishra (Fictional)',
    workType: 'Community Sanitation Units',
    sector: 'Community Sanitation Units',
    implementingAgency: 'Puri Municipality Engineering Cell',
    financialYear: 'FY 2024-25',
    sanctionDate: '2024-05-25',
    startDate: '2024-05-25',
    expectedCompletion: '2024-12-20',
    sanctionAmountLakhs: 19.50,
    releasedAmountLakhs: 15.00,
    expenditureLakhs: 12.00,
    physicalProgress: 50,
    status: 'Ongoing',
    riskLevel: 'Low Risk',
    reviewFlag: true,
    flagCategory: 'Monsoon Interruption',
    flagSeverity: 'low',
    flagReason: 'Monsoon weather pause logged by executing cell; physical execution resumed on schedule.',
    anomalyReason: 'Monsoon weather pause logged by executing cell; physical execution resumed on schedule.',
  }
];

export const ANOMALY_SCATTER_DATA = [
  // Normal parity samples
  { id: 1, workCode: 'MPLADS-2024-0012', progress: 10, expenditurePercent: 12, isAnomaly: false, category: 'Normal' },
  { id: 2, workCode: 'MPLADS-2024-0034', progress: 25, expenditurePercent: 28, isAnomaly: false, category: 'Normal' },
  { id: 3, workCode: 'MPLADS-2024-0056', progress: 40, expenditurePercent: 42, isAnomaly: false, category: 'Normal' },
  { id: 4, workCode: 'MPLADS-2024-0089', progress: 55, expenditurePercent: 52, isAnomaly: false, category: 'Normal' },
  { id: 5, workCode: 'MPLADS-2024-0120', progress: 70, expenditurePercent: 68, isAnomaly: false, category: 'Normal' },
  { id: 6, workCode: 'MPLADS-2024-0155', progress: 85, expenditurePercent: 88, isAnomaly: false, category: 'Normal' },
  { id: 7, workCode: 'MPLADS-2024-0201', progress: 95, expenditurePercent: 96, isAnomaly: false, category: 'Normal' },
  { id: 8, workCode: 'MPLADS-2024-0245', progress: 100, expenditurePercent: 100, isAnomaly: false, category: 'Normal' },
  { id: 9, workCode: 'MPLADS-2024-0300', progress: 60, expenditurePercent: 62, isAnomaly: false, category: 'Normal' },
  { id: 10, workCode: 'MPLADS-2024-0322', progress: 30, expenditurePercent: 32, isAnomaly: false, category: 'Normal' },

  // Statistical Outliers (High Spend / Low Progress)
  { id: 11, workCode: 'MPLADS-2024-0412', progress: 24, expenditurePercent: 92, isAnomaly: true, category: 'High Disbursement / Low Progress' },
  { id: 12, workCode: 'MPLADS-2024-0823', progress: 20, expenditurePercent: 85, isAnomaly: true, category: 'High Disbursement / Low Progress' },
  { id: 13, workCode: 'MPLADS-2024-0550', progress: 15, expenditurePercent: 78, isAnomaly: true, category: 'High Disbursement / Low Progress' },
  { id: 14, workCode: 'MPLADS-2024-0610', progress: 32, expenditurePercent: 95, isAnomaly: true, category: 'High Disbursement / Low Progress' },
  
  // Statistical Outliers (Cost Escalation > 120%)
  { id: 15, workCode: 'MPLADS-2023-1104', progress: 88, expenditurePercent: 129, isAnomaly: true, category: 'Cost Variance > 25%' },
  { id: 16, workCode: 'MPLADS-2023-0988', progress: 90, expenditurePercent: 134, isAnomaly: true, category: 'Cost Variance > 25%' },
  
  // Statistical Outliers (Stalled / Inactivity with advance)
  { id: 17, workCode: 'MPLADS-2024-0198', progress: 35, expenditurePercent: 50, isAnomaly: true, category: 'Timeline Inactivity' },
  { id: 18, workCode: 'MPLADS-2024-0771', progress: 12, expenditurePercent: 45, isAnomaly: true, category: 'Timeline Inactivity' },
];

/**
 * Reusable helper to locate a project record by ID or Code (case-insensitive)
 */
export function getProjectById(identifier) {
  if (!identifier) return null;
  const cleanId = String(identifier).trim().toLowerCase();
  
  // Direct match on code or id
  const directMatch = MOCK_PROJECTS.find(
    (p) =>
      (p.id && p.id.toLowerCase() === cleanId) ||
      (p.code && p.code.toLowerCase() === cleanId)
  );
  if (directMatch) return directMatch;

  // Check if identifier matches an alert workCode or id
  const alertMatch = RECENT_ANOMALY_ALERTS.find(
    (a) =>
      (a.id && a.id.toLowerCase() === cleanId) ||
      (a.workCode && a.workCode.toLowerCase() === cleanId)
  );
  if (alertMatch) {
    const matchedPrj = MOCK_PROJECTS.find(
      (p) => p.code && p.code.toLowerCase() === alertMatch.workCode.toLowerCase()
    );
    if (matchedPrj) {
      return { ...matchedPrj, ...alertMatch, code: matchedPrj.code || alertMatch.workCode };
    }
  }

  return null;
}
