import { ShieldCheck, Info } from 'lucide-react';

/**
 * Standardized Government Analytics Governance & Non-Accusatory Disclaimer Banner
 */
export default function DisclaimerBanner({ className = '', compact = false }) {
  if (compact) {
    return (
      <div className={`flex items-center gap-2 px-3 py-2 bg-sky-50/70 border border-sky-200/80 rounded-lg text-xs text-sky-900 ${className}`}>
        <Info className="w-4 h-4 text-sky-600 shrink-0" />
        <span>
          <strong>Administrative Notice:</strong> Model-flagged works highlight statistical deviations, cost variances, or milestone delays to prioritize nodal verification. They do not constitute findings of irregularity.
        </span>
      </div>
    );
  }

  return (
    <div className={`bg-gradient-to-r from-sky-50/80 via-white to-sky-50/40 border border-sky-200/80 rounded-xl p-4 shadow-xs flex items-start gap-3.5 ${className}`}>
      <div className="w-8 h-8 rounded-lg bg-sky-100 text-sky-700 flex items-center justify-center shrink-0 mt-0.5 border border-sky-200">
        <ShieldCheck className="w-5 h-5" />
      </div>
      <div className="text-xs space-y-1">
        <div className="font-semibold text-sky-950 flex items-center gap-2">
          <span>Official Oversight & Analytical Advisory Notice</span>
          <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 bg-sky-100 text-sky-800 rounded">
            Audit Decision Support
          </span>
        </div>
        <p className="text-slate-600 leading-relaxed">
          The indicators and anomaly flags generated by this platform serve as automated analytical heuristics to assist district nodal officers and monitoring committees. Flagged records indicate statistical divergence (e.g. expenditure velocity vs. physical progress or prolonged inactivity) and are flagged strictly for administrative field inspection and record reconciliation.
        </p>
      </div>
    </div>
  );
}
